### ISSUE TITLE
Leap year handling

### ISSUE THREAD

**Issue by chopchop505** [StatEngine/shiftly#18]
Delaware has a shift change next year to handle leap year.
How should we handle?

```
Our shifts are straight 24/48 hr shifts.

  3/21/19 – Unit 1 or A

  3/21/19 – Unit 2 or B

  3/23/19 – Unit 3 or C
Repeat….

  3/24/19 – Unit 1 or A

  3/25/19 – Unit 2 or B

  3/26/19 – Unit 3 or C
The only change with this is Leap year. On February 29, the personnel work 8 hrs and the day is skipped as a shift day.

  2/28/20 – Unit 3 or C

  2/29/20

  0800-1600 – Unit 3 or C

  1600-0000 – Unit 2 or B

  0000-0800 – Unit 1 or A

  3/01/20 – Unit 1 or A

  3/02/20 – Unit 2 or B
Repeat Cycle

  3/03/20 – Unit 3 or C

  3/04/20 – Unit 1 or A

  3/05/20 – Unit 2 or B
```

**Comment by chopchop505** [comment]
@garnertb ideas?

**Comment by chopchop505** [comment]
Its not really a big deal right now because we get shift information for RMS, the only thing that would be wrong are other shiftly clients (displays on frontend, emails) only on  leap day.

**Comment by chopchop505** [comment]
But I wonder if other departments are going to have funkiness on leap day.

**Comment by garnertb** [comment]
Never heard of this.  Off the top of my head, probably just need some way
to handle these type of edge cases in a config object.

**Comment by andersonad** [comment]
+1, Columbus Ohio also maintains this type of leap-day work schedule

**Comment by andersonad** [comment]
Note, other fire departments simply continue their shift schedule as normal, with the leap day just being another day. A leap day solution is fire department specific :slightly_frowning_face:

**Comment by andersonad** [comment]
> Its not really a big deal right now because we get shift information from them from RMS, the only thing that would be wrong are other shiftly clients (displays on frontend, emails) only on leap day.

Wouldn't a leap day that's not skipped introduce an off-by-one error in the shifts of those departments? Or does it auto-correct?
